name: uni_links_example
description: Demonstrates how to use the uni_links plugin.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  uni_links:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
